aws-dash:
  aws:
    credentials:
      secret-key: N/HD8zHt6iLY7kDxx4mmfRQ9MQ4skF+7acZSLsum
      access-key: AKIAXS6GF47LGDYSXPP3
    region: ap-south-1
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false